#ifndef __USB_PHY_H__
#define __USB_PHY_H__

typedef struct
{
    __I  uint32_t PHYID             ; /* 0x5550_A000 PHY Identification Register */
    __IO uint32_t PLL_CTRL_0        ; /* 0x5550_A004 PLL Control Register 0 */
    __IO uint32_t PLL_CTRL_1        ; /* 0x5550_A008 PLL Control Register 1 */
    __IO uint32_t PLL_CTRL_2        ; /* 0x5550_A00C PLL Control Register 2 */
    __IO uint32_t TX_CH_CTRL_0      ; /* 0x5550_A010 Tx Channel Control Register 0 */
    __IO uint32_t TX_CH_CTRL_1      ; /* 0x5550_A014 Tx Channel Control Register 1 */
    __IO uint32_t TX_CH_CTRL_2      ; /* 0x5550_A018 Tx Channel Control Register 2 */
    __IO uint32_t TX_CH_CTRL_3      ; /* 0x5550_A01C Tx Channel Control Register 3 */
    __IO uint32_t RX_CH_CTRL_0      ; /* 0x5550_A020 Rx Channel Control Register 0 */
    __IO uint32_t RX_CH_CTRL_1      ; /* 0x5550_A024 Rx Channel Control Register 1 */
    __IO uint32_t RX_CH_CTRL_2      ; /* 0x5550_A028 Rx Channel Control Register 2 */
    __IO uint32_t RX_CH_CTRL_3      ; /* 0x5550_A02C Rx Channel Control Register 3 */
    __IO uint32_t ANALOG_CTRL_0     ; /* 0x5550_A030 Analog Top Control Register 0 */
    __IO uint32_t ANALOG_CTRL_1     ; /* 0x5550_A034 Analog Top Control Register 1 */
    __IO uint32_t ANALOG_CTRL_2     ; /* 0x5550_A038 Analog Top Control Register 2 */
    __IO uint32_t DIGITAL_CTRL_0    ; /* 0x5550_A03C Digital Control Register 0 */
    __IO uint32_t DIGITAL_CTRL_1    ; /* 0x5550_A040 Digital Control Register 1 */
    __IO uint32_t DIGITAL_CTRL_2    ; /* 0x5550_A044 Digital Control Register 2 */
    __IO uint32_t DIGITAL_CTRL_3    ; /* 0x5550_A048 Digital Control Register 3 */
    __IO uint32_t TEST_CTRL_0       ; /* 0x5550_A04C Test Control and Status Register 0 */
    __IO uint32_t TEST_CTRL_1       ; /* 0x5550_A050 Test Control and Status Register 1 */
    __IO uint32_t TEST_CTRL_2       ; /* 0x5550_A054 Test Control and Status Register 2 */
    __IO uint32_t CHARGERDTCT_CTRL  ; /* 0x5550_A058 Charger Detector Control Register */
    __IO uint32_t OTG_CTRL_0        ; /* 0x5550_A05C OTG Control Register 0 */
    __IO uint32_t PHY_MON_STATUS    ; /* 0x5550_A060 Read PHY_MON[15:0] */
    // __IO uint32_t RESERVED_REG      ; /* 0x5550_A064 Reserved Register */
    __IO uint32_t  DIGITAL_CTRL_4      ;     /* 0x4240_5E64 Digital Control Register 4 EMEI C0*/
    __IO uint32_t RESERVED0[4];

    __I  uint32_t INTERNALCID_0     ; /* 0x5550_A078 USB2 Internal CID Register 0 */
    __I  uint32_t INTERNALCID_1     ; /* 0x5550_A07C USB2 Internal CID Register 1 */
} EMEI_USB_PHY_TypeDef;

#define    USB_PHY_BASE                          0xD4207000   //emei                       
#define    EMEI_USB_PHY  (( EMEI_USB_PHY_TypeDef *) USB_PHY_BASE )

/* PHY Identification Register (PHY_ID) */
#define USB_PHY_PHY_ID_CID0_MSK     SHIFT8(0xff)
#define USB_PHY_PHY_ID_CID0_BASE    8
#define USB_PHY_PHY_ID_CID1_MSK     SHIFT0(0xff)
#define USB_PHY_PHY_ID_CID1_BASE    0

/* PLL Control Register 0 (PLL_CTRL_0) */
#define USB_PHY_PLL_CTRL_0_PLLVDD18_MSK     SHIFT14(0x3)
#define USB_PHY_PLL_CTRL_0_PLLVDD18_BASE    14
//#define USB_PHY_PLL_CTRL_0_PLLVDD12_MSK     SHIFT12(0x3)
//#define USB_PHY_PLL_CTRL_0_PLLVDD12_BASE    12
//#define USB_PHY_PLL_CTRL_0_REFDIV_MSK     SHIFT8(0xf)
//#define USB_PHY_PLL_CTRL_0_REFDIV_BASE    8
#define USB_PHY_PLL_CTRL_0_REFDIV_MSK     SHIFT9(0x1f)
#define USB_PHY_PLL_CTRL_0_REFDIV_BASE    9              //EMEI C0

#define USB_PHY_PLL_CTRL_0_FBDIV_MSK     SHIFT0(0x1ff)
#define USB_PHY_PLL_CTRL_0_FBDIV_BASE    0          //EMEI C0

/* PLL Control Register 1 (PLL_CTRL_1) */
#define USB_PHY_PLL_CTRL_1_PLL_READY     BIT_15
#define USB_PHY_PLL_CTRL_1_PLL_CONTROL_BY_PIN     BIT_14
#define USB_PHY_PLL_CTRL_1_PU_PLL     BIT_13
#define USB_PHY_PLL_CTRL_1_PLL_LOCK_BYPASS     BIT_12
#define USB_PHY_PLL_CTRL_1_LOCKDET_ISEL     BIT_11
#define USB_PHY_PLL_CTRL_1_ICP_MSK  SHIFT8(0x7)
#define USB_PHY_PLL_CTRL_1_ICP_BASE 8
#define USB_PHY_PLL_CTRL_1_KVCO_EXT     BIT_7
#define USB_PHY_PLL_CTRL_1_KVCO_MSK SHIFT4(0x7)
#define USB_PHY_PLL_CTRL_1_KVCO_BASE    4
#define USB_PHY_PLL_CTRL_1_CLK_BLK_EN     BIT_3
#define USB_PHY_PLL_CTRL_1_VCOCAL_START     BIT_2
#define USB_PHY_PLL_CTRL_1_PLLCAL12_MSK SHIFT0(0x3)
#define USB_PHY_PLL_CTRL_1_PLLCAL12_BASE     0




/* Tx Channel Control Register 0 (TX_CH_CTRL_0) */
#define USB_PHY_TX_CH_CTRL_0_TXDATA_BLOCK_EN   BIT_14
#define USB_PHY_TX_CH_CTRL_0_RCAL_START   BIT_13
#define USB_PHY_TX_CH_CTRL_0_EXT_HS_RCAL_EN   BIT_12
#define USB_PHY_TX_CH_CTRL_0_EXT_FS_RCAL_EN   BIT_11
#define USB_PHY_TX_CH_CTRL_0_IMPCAL_VTH_MSK SHIFT8(0x7)
#define USB_PHY_TX_CH_CTRL_0_IMPCAL_VTH_BASE    8
#define USB_PHY_TX_CH_CTRL_0_EXT_HS_RCAL_MSK    SHIFT4(0xf)
#define USB_PHY_TX_CH_CTRL_0_EXT_HS_RCAL_BASE   4
#define USB_PHY_TX_CH_CTRL_0_EXT_FS_RCAL_MSK    SHIFT0(0xf)
#define USB_PHY_TX_CH_CTRL_0_EXT_FS_RCAL_BASE   0

/* Tx Channel Control Register 1 (TX_CH_CTRL_1) */
#define USB_PHY_TX_CH_CTRL_1_TXVDD15_MSK   SHIFT10(0x3)
#define USB_PHY_TX_CH_CTRL_1_TXVDD15_BASE   10
#define USB_PHY_TX_CH_CTRL_1_TXVDD12_MSK   SHIFT8(0x3)
#define USB_PHY_TX_CH_CTRL_1_TXVDD12_BASE  8
#define USB_PHY_TX_CH_CTRL_1_LOWVDD_EN  BIT_7
#define USB_PHY_TX_CH_CTRL_1_AMP_MSK   SHIFT4(0x7)
#define USB_PHY_TX_CH_CTRL_1_AMP_BASE  4
#define USB_PHY_TX_CH_CTRL_1_CK60_PHSEL_MSK   SHIFT0(0xf)
#define USB_PHY_TX_CH_CTRL_1_CK60_PHSEL_BASE  0

/* Tx Channel Control Register 2 (TX_CH_CTRL_2) */
#define USB_PHY_TX_CH_CTRL_2_DRV_SLEWRATE_MSK   SHIFT10(0x3)
#define USB_PHY_TX_CH_CTRL_2_DRV_SLEWRATE_BASE  10
#define USB_PHY_TX_CH_CTRL_2_IMP_CAL_DLY_MSK   SHIFT8(0x3)
#define USB_PHY_TX_CH_CTRL_2_IMP_CAL_DLY_BASE  8
#define USB_PHY_TX_CH_CTRL_2_FSDRV_EN_MSK   SHIFT4(0xf)
#define USB_PHY_TX_CH_CTRL_2_FSDRV_EN_BASE  4
#define USB_PHY_TX_CH_CTRL_2_HSDRV_EN_MSK   SHIFT0(0xf)
#define USB_PHY_TX_CH_CTRL_2_HSDRV_EN_BASE  0

/* Rx Channel Control Register 0 (RX_CH_CTRL_0) */
#define USB_PHY_RX_CH_CTRL_0_PHASE_FREEZE_DLY   BIT_15
#define USB_PHY_RX_CH_CTRL_0_USQ_LENGTH   BIT_14
#define USB_PHY_RX_CH_CTRL_0_ACQ_LENGTH_MSK   SHIFT12(0x3)
#define USB_PHY_RX_CH_CTRL_0_ACQ_LENGTH_BASE 12
#define USB_PHY_RX_CH_CTRL_0_SQ_LENGTH_MSK   SHIFT10(0x3)
#define USB_PHY_RX_CH_CTRL_0_SQ_LENGTH_BASE  10
#define USB_PHY_RX_CH_CTRL_0_DISCON_THRESH_MSK   SHIFT8(0x3)
#define USB_PHY_RX_CH_CTRL_0_DISCON_THRESH_BASE  8
#define USB_PHY_RX_CH_CTRL_0_SQ_THRESH_MSK   SHIFT4(0xf)
#define USB_PHY_RX_CH_CTRL_0_SQ_THRESH_BASE  4
#define USB_PHY_RX_CH_CTRL_0_LPF_COEF_MSK   SHIFT2(0x3)
#define USB_PHY_RX_CH_CTRL_0_LPF_COEF_BASE  2
#define USB_PHY_RX_CH_CTRL_0_INTPI_MSK   SHIFT0(0x3)
#define USB_PHY_RX_CH_CTRL_0_INTPI_BASE  0

/* Rx Channel Control Register 1 (RX_CH_CTRL_1) */
#define USB_PHY_RX_CH_CTRL_1_EARLY_VOS_ON_EN   BIT_13
#define USB_PHY_RX_CH_CTRL_1_RXDATA_BLOCK_EN   BIT_12
#define USB_PHY_RX_CH_CTRL_1_EDGE_DET_EN   BIT_11
#define USB_PHY_RX_CH_CTRL_1_CAP_SEL_MSK   SHIFT8(0x7)
#define USB_PHY_RX_CH_CTRL_1_CAP_SEL_BASE 8
#define USB_PHY_RX_CH_CTRL_1_RXDATA_BLOCK_LENGTH_MSK   SHIFT6(0x3)
#define USB_PHY_RX_CH_CTRL_1_RXDATA_BLOCK_LENGTH_BASE   6
#define USB_PHY_RX_CH_CTRL_1_EDGE_DET_SEL_MSK   SHIFT4(0x3)
#define USB_PHY_RX_CH_CTRL_1_EDGE_DET_SEL_BASE 4
#define USB_PHY_RX_CH_CTRL_1_CDR_COEF_SEL   BIT_3
#define USB_PHY_RX_CH_CTRL_1_CDR_FASTLOCK_EN   BIT_2
#define USB_PHY_RX_CH_CTRL_1_S2TO3_DLY_SEL_MSK   SHIFT0(0x3)
#define USB_PHY_RX_CH_CTRL_1_S2TO3_DLY_SEL_BASE  0

/* Rx Channel Control Register 2 (RX_CH_CTRL_2) */
#define USB_PHY_RX_CH_CTRL_2_USQ_FILTER   BIT_8
#define USB_PHY_RX_CH_CTRL_2_SQ_CM_SEL   BIT_7
#define USB_PHY_RX_CH_CTRL_2_SAMPLER_CTRL   BIT_6
#define USB_PHY_RX_CH_CTRL_2_SQ_BUFFER_EN   BIT_5
#define USB_PHY_RX_CH_CTRL_2_SQ_ALWAYS_ON   BIT_4
#define USB_PHY_RX_CH_CTRL_2_RXVDD18_MSK   SHIFT2(0x3)
#define USB_PHY_RX_CH_CTRL_2_RXVDD18_BASE  2
#define USB_PHY_RX_CH_CTRL_2_RXVDD12_MSK   SHIFT0(0x3)
#define USB_PHY_RX_CH_CTRL_2_RXVDD12_BASE  0

/* Analog Top Control Register 0 (ANALOG_CTRL_0) */
#define USB_PHY_ANALOG_CTRL_0_BG_VSEL_MSK  SHIFT8(0x3)
#define USB_PHY_ANALOG_CTRL_0_BG_VSEL_BASE 8
#define USB_PHY_ANALOG_CTRL_0_DIG_SEL_MSK  SHIFT6(0x3)
#define USB_PHY_ANALOG_CTRL_0_DIG_SEL_BASE 6
#define USB_PHY_ANALOG_CTRL_0_TOPVDD18_MSK  SHIFT4(0x3)
#define USB_PHY_ANALOG_CTRL_0_TOPVDD18_BASE 4
#define USB_PHY_ANALOG_CTRL_0_VDD_USB2_DIG_TOP_SEL  BIT_3
#define USB_PHY_ANALOG_CTRL_0_IPTAT_SEL_MSK  SHIFT0(0x7)
#define USB_PHY_ANALOG_CTRL_0_IPTAT_SEL_BASE 0

/* Analog Top Control Register 1 (ANALOG_CTRL_1) */
#define USB_PHY_ANALOG_CTRL_1_PU_ANA  BIT_14
#define USB_PHY_ANALOG_CTRL_1_ANA_CONTROL_BY_PIN  BIT_13
#define USB_PHY_ANALOG_CTRL_1_PLL_SEL_LPFR  BIT_12
#define USB_PHY_ANALOG_CTRL_1_PLL_V2I_EXT  BIT_11
#define USB_PHY_ANALOG_CTRL_1_PLL_V2I_MSK  SHIFT8(0x7)
#define USB_PHY_ANALOG_CTRL_1_PLL_V2I_BASE 8
#define USB_PHY_ANALOG_CTRL_1_R_ROTATE_SEL  BIT_7
#define USB_PHY_ANALOG_CTRL_1_STRESS_TEST_MODE  BIT_6
#define USB_PHY_ANALOG_CTRL_1_TESTMON_ANA_MSK  SHIFT0(0x3f)
#define USB_PHY_ANALOG_CTRL_1_TESTMON_ANA_BASE 0

/* Digital Control Register 0 (DIGITAL_CTRL_0) */
#define USB_PHY_DIGITAL_CTRL_0_FIFO_UF  BIT_15
#define USB_PHY_DIGITAL_CTRL_0_FIFO_OV  BIT_14
#define USB_PHY_DIGITAL_CTRL_0_FS_EOP_MODE  BIT_13
#define USB_PHY_DIGITAL_CTRL_0_HOST_DISCON_SEL1  BIT_12
#define USB_PHY_DIGITAL_CTRL_0_HOST_DISCON_SEL0  BIT_11
#define USB_PHY_DIGITAL_CTRL_0_FORCE_END_EN  BIT_10
#define USB_PHY_DIGITAL_CTRL_0_EARLY_TX_EN  BIT_9
#define USB_PHY_DIGITAL_CTRL_0_SYNCDET_WINDOW_EN  BIT_8
#define USB_PHY_DIGITAL_CTRL_0_CLK_SUSPEND_EN  BIT_7
#define USB_PHY_DIGITAL_CTRL_0_HS_DRIBBLE_EN  BIT_6
#define USB_PHY_DIGITAL_CTRL_0_SYNC_NUM_MSK  SHIFT4(0x3)
#define USB_PHY_DIGITAL_CTRL_0_SYNC_NUM_BASE 4
#define USB_PHY_DIGITAL_CTRL_0_FIFO_FILL_NUM_MSK  SHIFT0(0xf)
#define USB_PHY_DIGITAL_CTRL_0_FIFO_FILL_NUM_BASE 0

/* Digital Control Register 1 (DIGITAL_CTRL_1) */
#define USB_PHY_DIGITAL_CTRL_1_FS_RX_ERROR_MODE2  BIT_15
#define USB_PHY_DIGITAL_CTRL_1_FS_RX_ERROR_MODE1  BIT_14
#define USB_PHY_DIGITAL_CTRL_1_FS_RX_ERROR_MODE  BIT_13
#define USB_PHY_DIGITAL_CTRL_1_CLK_OUT_SEL  BIT_12
#define USB_PHY_DIGITAL_CTRL_1_EXT_TX_CLK_SEL  BIT_11
#define USB_PHY_DIGITAL_CTRL_1_ARC_DPDM_MODE  BIT_10
#define USB_PHY_DIGITAL_CTRL_1_DP_PULLDOWN  BIT_9
#define USB_PHY_DIGITAL_CTRL_1_DM_PULLDOWN  BIT_8
#define USB_PHY_DIGITAL_CTRL_1_SYNC_IGNORE_SQ  BIT_7
#define USB_PHY_DIGITAL_CTRL_1_SQ_RST_RX  BIT_6
#define USB_PHY_DIGITAL_CTRL_1_MON_SEL_MSK  SHIFT0(0x3f)
#define USB_PHY_DIGITAL_CTRL_1_MON_SEL_BASE 0

/* Digital Control Register 2 (DIGITAL_CTRL_2) */
#define USB_PHY_DIGITAL_CTRL_2_PAD_STRENGTH_MSK  SHIFT8(0x1f)
#define USB_PHY_DIGITAL_CTRL_2_PAD_STRENGTH_BASE 8
#define USB_PHY_DIGITAL_CTRL_2_LONG_EOP  BIT_5
#define USB_PHY_DIGITAL_CTRL_2_NOVBUS_DPDM00  BIT_4
#define USB_PHY_DIGITAL_CTRL_2_DISABLE_EL16  BIT_3
#define USB_PHY_DIGITAL_CTRL_2_ALIGN_FS_OUTEN  BIT_2
#define USB_PHY_DIGITAL_CTRL_2_HS_HDL_SYNC  BIT_1
#define USB_PHY_DIGITAL_CTRL_2_FS_HDL_OPMD  BIT_0


//Test Control and Status Register 0 (TEST_CTRL_0) EMEI C0
#define USB_PHY_TEST_CTRL_0_TEST_DIG_LPBK      BIT_15
#define USB_PHY_TEST_CTRL_0_TEST_LPBK_EN      BIT_14
#define USB_PHY_TEST_CTRL_0_TEST_BYPASS      BIT_11
#define USB_PHY_TEST_CTRL_0_TEST_LENGTH_MSK   SHIFT12(0x3)
#define USB_PHY_TEST_CTRL_0_TEST_LENGTH_BASE     12
#define USB_PHY_TEST_CTRL_0_TEST_MODE_MSK   SHIFT8(0x7)
#define USB_PHY_TEST_CTRL_0_TEST_MODE_BASE     8
#define USB_PHY_TEST_CTRL_0_TEST_TX_PATTERN_MSK   SHIFT0(0xff)
#define USB_PHY_TEST_CTRL_0_TEST_TX_PATTERN_BASE     0


//Test Control and Status Register 1 (TEST_CTRL_1) EMEI C0
#define USB_PHY_TEST_CTRL_1_TEST_DONE  BIT_15
#define USB_PHY_TEST_CTRL_1_TEST_FLAG  BIT_14
#define USB_PHY_TEST_CTRL_1_TEST_EN    BIT_13
#define USB_PHY_TEST_CTRL_1_TEST_RESET  BIT_12
#define USB_PHY_TEST_CTRL_1_TEST_UTMI_SEL  BIT_7
#define USB_PHY_TEST_CTRL_1_TEST_SUSPENDM  BIT_6
#define USB_PHY_TEST_CTRL_1_TEST_TX_BITSTUFF_EN  BIT_5
#define USB_PHY_TEST_CTRL_1_TEST_TERM_SELECT  BIT_4
#define USB_PHY_TEST_CTRL_1_TEST_SKIP_MSK   SHIFT8(0x7)
#define USB_PHY_TEST_CTRL_1_TEST_SKIP_BASE  8
#define USB_PHY_TEST_CTRL_1_TEST_OP_MODE_MSK   SHIFT2(0x3)
#define USB_PHY_TEST_CTRL_1_TEST_OP_MODE_BASE  2
#define USB_PHY_TEST_CTRL_1_TEST_XCVR_SELECT_MSK   SHIFT0(0x3)
#define USB_PHY_TEST_CTRL_1_TEST_XCVR_SELECT_BASE  0




/* Charger Detector Control Register (CHARGERDTCT_CTRL) */
#define USB_PHY_CHARGERDTCT_CTRL_ENABLE_SWITCH  BIT_3
#define USB_PHY_CHARGERDTCT_CTRL_PU_CHRG_DTC  BIT_2
#define USB_PHY_CHARGERDTCT_CTRL_TESTMON_CHRGDTC_MSK  SHIFT0(0x3)
#define USB_PHY_CHARGERDTCT_CTRL_TESTMON_CHRGDTC_BASE 0

/* OTG Control Register 0 (OTG_CTRL_0) */
#define USB_PHY_OTG_CTRL_0_OTG_CONTROL_BY_PIN     BIT_4
#define USB_PHY_OTG_CTRL_0_PU_OTG     BIT_3
#define USB_PHY_OTG_CTRL_0_TESTMON_OTG_MSK     SHIFT0(0x7)
#define USB_PHY_OTG_CTRL_0_TESTMON_OTG_BASE  0

/* Read PHY_MON[15:0] (PHY_MON_STATUS) */
#define USB_PHY_PHY_MON_STATUS_MSK     SHIFT0(0xffff)
#define USB_PHY_PHY_MON_STATUS_BASE    0


//USB2_RESERVE_REG0   EMEI C0
#define USB2_RESERVE_REG0_DP_DM_SWAP_CTRL  BIT_15
#define USB2_RESERVE_REG0_PLLVDD12_MSK   SHIFT12(0x3)
#define USB2_RESERVE_REG0_PLLVDD12_BASE    12
#define USB2_RESERVE_REG0_VSRC_CHARGE_MSK   SHIFT12(0x3)
#define USB2_RESERVE_REG0_VSRC_CHARGE_BASE    10
#define USB2_RESERVE_REG0_VDAT_CHARGE_MSK   SHIFT12(0x3)
#define USB2_RESERVE_REG0_VDAT_CHARGE_BASE    12
#define USB2_RESERVE_REG0_ENABLE_SWITCH_DP  BIT_7
#define USB2_RESERVE_REG0_ENABLE_SWITCH_DM  BIT_6
#define USB2_RESERVE_REG0_CDP_DM_AUTO_SWITCH  BIT_5
#define USB2_RESERVE_REG0_PD_EN  BIT_4
#define USB2_RESERVE_REG0_DCP_EN  BIT_3
#define USB2_RESERVE_REG0_CDP_EN  BIT_2

/* USB2 Internal CID Register 0 (INTERNALCID_0) */
#define USB_PHY_INTERNALCID_0_GEOMETRY_MSK     SHIFT12(0xf)
#define USB_PHY_INTERNALCID_0_GEOMETRY_BASE    12
#define USB_PHY_INTERNALCID_0_PROCESS_MSK     SHIFT10(0x3)
#define USB_PHY_INTERNALCID_0_PROCESS_BASE    10
#define USB_PHY_INTERNALCID_0_FOUNDRY_MSK     SHIFT8(0x3)
#define USB_PHY_INTERNALCID_0_FOUNDRY_BASE    8
#define USB_PHY_INTERNALCID_0_MAJOR_REVISION_MSK     SHIFT4(0xf)
#define USB_PHY_INTERNALCID_0_MAJOR_REVISION_BASE    4
#define USB_PHY_INTERNALCID_0_MINOR_REVISION_MSK     SHIFT0(0xf)
#define USB_PHY_INTERNALCID_0_MINOR_REVISION_BASE    0

/* USB2 Internal CID Register 1 (INTERNALCID_1) */
#define USB_PHY_INTERNALCID_1__MSK     SHIFT(0x)
#define USB_PHY_INTERNALCID_1__BASE
#define USB_PHY_INTERNALCID_1_THRESHOLD_MSK     SHIFT10(0x3)
#define USB_PHY_INTERNALCID_1_THRESHOLD_BASE    10
#define USB_PHY_INTERNALCID_1_ANALOG_VOLTAGE_MSK     SHIFT8(0x3)
#define USB_PHY_INTERNALCID_1_ANALOG_VOLTAGE_BASE  8
#define USB_PHY_INTERNALCID_1_PHY_OTG     BIT_7
#define USB_PHY_INTERNALCID_1_PHY_CHG_DTC     BIT_6
#define USB_PHY_INTERNALCID_1_PHY_HSIC     BIT_5
#define USB_PHY_INTERNALCID_1_PHY_ULPI     BIT_4
#define USB_PHY_INTERNALCID_1_DIG_REGULATOR     BIT_3
#define USB_PHY_INTERNALCID_1_PHY_MULTIPORT     BIT_0




#endif
