#ifndef __CCIC_H__
#define __CCIC_H__

typedef struct
{
   __IO uint32_t Y0_BASE_ADDR;//0x00 OFFSET Y0-Base Address Register
   __IO uint32_t Y1_BASE_ADDR;//0x04 OFFSET Y1-Base Address Register
   __IO uint32_t Y2_BASE_ADDR;//0x08 OFFSET Y2-Base Address Register
   __IO uint32_t U0_BASE_ADDR;//0x0C OFFSET U0-Base Address Register
   __IO uint32_t U1_BASE_ADDR;//0x10 OFFSET U1-Base Address Register
   __IO uint32_t U2_BASE_ADDR;//0x14 OFFSET U2-Base Address Register
   __IO uint32_t V0_BASE_ADDR;//0x18 OFFSET V0-Base Address Register
   __IO uint32_t V1_BASE_ADDR;//0x1C OFFSET V1-Base Address Register
   __IO uint32_t V2_BASE_ADDR;//0x20 OFFSET V2-Base Address Register
   __IO uint32_t IMG_PITCH;//0x24 OFFSET   Image Pitch Register
   __IO uint32_t IRQ_RAW_STATUS;//0x28 OFFSET  IRQ RAW Status Register
   __IO uint32_t IRQ_MASK;//0x2C OFFSET IRQ Mask Register
   __IO uint32_t IRQ_STATUS;//0x30 OFFSET IRQ Status Register
   __IO uint32_t IMG_SIZE;//0x34 OFFSET Image Size Register
   __IO uint32_t IMG_OFFSET;//0x38 OFFSET Image Offset Register
   __IO uint32_t CTRL_0;//0x3C OFFSET Control 0 Register
   __IO uint32_t CTRL_1;//0x40 OFFSET Control 1 Register
   __IO uint32_t CTRL_2;//0x44 OFFSET Control 2 Register
   __IO uint32_t CTRL_3;//0x44 OFFSET Control 2 Register
   __IO uint32_t RESERVED0[(0x60-0x48)/4-1];
   __IO uint32_t LNNUM;//0x60 OFFSET Line Number Register
   __IO uint32_t RESERVED1[(0x88-0x60)/4-1];
   __IO uint32_t CLOCK_CTRL;//0x88 OFFSET Clock Control Register
   __IO uint32_t SRAM_TC0_TEST_ONLY;//0x8C OFFSET SRAM TC0 Register (Test Only)
   __IO uint32_t SRAM_TC1_TEST_ONLY;//0x90 OFFSET SRAM TC1 Register (Test Only)
   __IO uint32_t RESERVED2[(0x100-0x90)/4-1];
   __IO uint32_t CSI2_CTRL_0;//0x100 OFFSET MIPI CSI2 Control 0 Register
   __IO uint32_t RESERVED3;
   __IO uint32_t CSI2_IRQ_RAW_STATUS;//0x108 OFFSET MIPI CSI2 IRQ Raw Status Register
   __IO uint32_t RESERVED4;
   __IO uint32_t CSI2_GSPFF;//0x110 OFFSET MIPI CSI2 GSP FIFO Register
   __IO uint32_t CSI2_VCCTRL;//0x114 OFFSET MIPI CSI2 Virtual Channel Control Register
   __IO uint32_t CSI2_VCCTRL2;//0x118 OFFSET MIPI CSI2 Virtual Channel Control Register
   __IO uint32_t RESERVED5[(0x12c-0x118)/4-1];
   __IO uint32_t CSI2_DPHY3;//0x12C OFFSET MIPI CSI2 DPHY 3 Register
   __IO uint32_t RESERVED6[(0x134-0x12c)/4-1];
   __IO uint32_t CSI2_DPHY5;//0x134 OFFSET MIPI CSI2 DPHY 5 Register
   __IO uint32_t CSI2_DPHY6;//0x138 OFFSET MIPI CSI2 DPHY 6 Register
   __IO uint32_t RESERVED7[(0x1FC-0x138)/4-1];
   __IO uint32_t CSI2_RESET;//0X1FC;
   __IO uint32_t START_DESC_CHAIN_ADDR_Y;//0x200 OFFSET Start Descriptor Chain Address Y Register
   __IO uint32_t START_DESC_CHAIN_ADDR_U;//0x204 OFFSET Start Descriptor Chain Address U Register
   __IO uint32_t START_DESC_CHAIN_ADDR_V;//0x208 OFFSET Start Descriptor Chain Address V Register
   __IO uint32_t DESC_CHAIN_LEN_Y;//0x20C OFFSET Descriptor Chain Length Y Register
   __IO uint32_t DESC_CHAIN_LEN_U;//0x210 OFFSET Descriptor Chain Length U Register
   __IO uint32_t DESC_CHAIN_LEN_V;//0x214 OFFSET Descriptor Chain Length V Register

   __IO uint32_t DESC_CHAIN_TADDR_Y;//0x218 OFFSET Descriptor Chain Target Address Y Register
   __IO uint32_t DESC_CHAIN_TADDR_U;//0x21C OFFSET Descriptor Chain Target Address U Register
   __IO uint32_t DESC_CHAIN_TADDR_V;//0x220 OFFSET Descriptor Chain Target Address U Register

   __IO uint32_t DESC_CHAIN_CTRLY;//0x224 OFFSET Descriptor Chain Control Y Register
   __IO uint32_t DESC_CHAIN_CTRLU;//0x228 OFFSET Descriptor Chain Control U Register
   __IO uint32_t DESC_CHAIN_CTRLV;//0x22C OFFSET Descriptor Chain Control V Register
   __IO uint32_t NEXT_DESC_CHAIN_ADDR_Y;//0x230 OFFSET Next Descriptor Chain Address Y Register
   __IO uint32_t NEXT_DESC_CHAIN_ADDR_U;//0x234 OFFSET Next Descriptor Chain Address U Register 
   __IO uint32_t NEXT_DESC_CHAIN_ADDR_V;//0x238 OFFSET Next Descriptor Chain Address V Register
   __IO uint32_t FRAME_BYTE_CNT;//0x23C OFFSET frame byte count

}CCIC_TypeDef;

#define    CCIC1_BASE  0xD420A000
#define    CCIC2_BASE  0xD420A800

#define    CCIC1  ((CCIC_TypeDef*)CCIC1_BASE)
#define    CCIC2  ((CCIC_TypeDef*)CCIC2_BASE)

//Image Pitch Register
#define IMG_PITCH_YPITCH_MSK     SHIFT2(0xfff)
#define IMG_PITCH_YPITCH_BASE       2
#define IMG_PITCH_UVPITCH_MSK     SHIFT18(0xfff)
#define IMG_PITCH_UVPITCH_BASE       18

//IRQ RAW Status Register
#define IRQ_RAW_STATUS_CSI2_GSPFF_ERR_IRQ     BIT_31
#define IRQ_RAW_STATUS_CSI2_GSPFF_VLD_IRQ     BIT_30
#define IRQ_RAW_STATUS_CSI2_PARSE_IRQ     BIT_29
#define IRQ_RAW_STATUS_CSI2_LNOVR_IRQ     BIT_28
#define IRQ_RAW_STATUS_CSI2_ECCCORR_IRQ     BIT_27
#define IRQ_RAW_STATUS_CSI2_ECCPAR_IRQ     BIT_26
#define IRQ_RAW_STATUS_CSI2_ECC2BIT_IRQ     BIT_25
#define IRQ_RAW_STATUS_CSI2_CRCERR_IRQ     BIT_24
#define IRQ_RAW_STATUS_CSI2_PKTERR_IRQ     BIT_23

#define IRQ_RAW_STATUS_DPHY_LNSOTERR_IRQ     BIT_17
#define IRQ_RAW_STATUS_DPHY_LNSOTSYNCERR_IRQ     BIT_16
#define IRQ_RAW_STATUS_DPHY_LNERRCTRL_IRQ     BIT_15
#define IRQ_RAW_STATUS_DPHY_LNULPSACTT_IRQ     BIT_14
#define IRQ_RAW_STATUS_DPHY_RXCLKULPS_IRQ     BIT_13
#define IRQ_RAW_STATUS_DPHY_RXCLKULPSACT_IRQ     BIT_12
#define IRQ_RAW_STATUS_AXI_WRERR_IRQ     BIT_11
#define IRQ_RAW_STATUS_DC_V_IRQ          BIT_10
#define IRQ_RAW_STATUS_DC_U_IRQ          BIT_9
#define IRQ_RAW_STATUS_DC_Y_IRQ          BIT_8
#define IRQ_RAW_STATUS_LINEIRQR          BIT_7
#define IRQ_RAW_STATUS_FIFOFULLIRQR      BIT_6
#define IRQ_RAW_STATUS_SOF2IRQR         BIT_5
#define IRQ_RAW_STATUS_SOF1IRQR         BIT_4
#define IRQ_RAW_STATUS_SOF0IRQR         BIT_3
#define IRQ_RAW_STATUS_EOF2IRQR         BIT_2
#define IRQ_RAW_STATUS_EOF1IRQR         BIT_1
#define IRQ_RAW_STATUS_EOF0IRQR         BIT_0

//IRQ Mask Register
#define IRQ_MASK_CSI2_GSPFF_ERR_IRQM     BIT_31
#define IRQ_MASK_CSI2_GSPFF_VLD_IRQM     BIT_30
#define IRQ_MASK_CSI2_PARSE_IRQM     BIT_29
#define IRQ_MASK_CSI2_LNOVR_IRQM     BIT_28
#define IRQ_MASK_CSI2_ECCCORR_IRQM     BIT_27
#define IRQ_MASK_CSI2_ECCPAR_IRQM     BIT_26
#define IRQ_MASK_CSI2_ECC2BIT_IRQM     BIT_25
#define IRQ_MASK_CSI2_CRCERR_IRQM     BIT_24
#define IRQ_MASK_CSI2_PKTERR_IRQM     BIT_23
#define IRQ_MASK_DPHY_LNSOTERR_IRQM     BIT_17
#define IRQ_MASK_DPHY_LNSOTSYNCERR_IRQM     BIT_16
#define IRQ_MASK_DPHY_LNERRCTRL_IRQM     BIT_15
#define IRQ_MASK_DPHY_LNULPSACTT_IRQM     BIT_14
#define IRQ_MASK_DPHY_RXCLKULPS_IRQM     BIT_13
#define IRQ_MASK_DPHY_RXCLKULPSACT_IRQM     BIT_12
#define IRQ_MASK_AXI_WRERR_IRQM     BIT_11
#define IRQ_MASK_DC_V_IRQM          BIT_10
#define IRQ_MASK_DC_U_IRQM          BIT_9
#define IRQ_MASK_DC_Y_IRQM          BIT_8
#define IRQ_MASK_LINEIRQRM          BIT_7
#define IRQ_MASK_FIFOFULLIRQM      BIT_6
#define IRQ_MASK_SOF2IRQM         BIT_5
#define IRQ_MASK_SOF1IRQM         BIT_4
#define IRQ_MASK_SOF0IRQM         BIT_3
#define IRQ_MASK_EOF2IRQM         BIT_2
#define IRQ_MASK_EOF1IRQM         BIT_1
#define IRQ_MASK_EOF0IRQM         BIT_0

//IRQ Status Register
#define IRQ_STATUS_CSI2_GSPFF_ERR_IRQS     BIT_31
#define IRQ_STATUS_CSI2_GSPFF_VLD_IRQS     BIT_30
#define IRQ_STATUS_CSI2_PARSE_IRQS     BIT_29
#define IRQ_STATUS_CSI2_LNOVR_IRQS     BIT_28
#define IRQ_STATUS_CSI2_ECCCORR_IRQS     BIT_27
#define IRQ_STATUS_CSI2_ECCPAR_IRQS     BIT_26
#define IRQ_STATUS_CSI2_ECC2BIT_IRQS     BIT_25
#define IRQ_STATUS_CSI2_CRCERR_IRQS     BIT_24
#define IRQ_STATUS_CSI2_PKTERR_IRQS     BIT_23
#define IRQ_STATUS_DPHY_LNSOTERR_IRQS     BIT_17
#define IRQ_STATUS_DPHY_LNSOTSYNCERR_IRQS     BIT_16
#define IRQ_STATUS_DPHY_LNERRCTRL_IRQS     BIT_15
#define IRQ_STATUS_DPHY_LNULPSACTT_IRQS     BIT_14
#define IRQ_STATUS_DPHY_RXCLKULPS_IRQS     BIT_13
#define IRQ_STATUS_DPHY_RXCLKULPSACT_IRQS     BIT_12
#define IRQ_STATUS_AXI_WRERR_IRQS     BIT_11
#define IRQ_STATUS_DC_V_IRQS          BIT_10
#define IRQ_STATUS_DC_U_IRQS          BIT_9
#define IRQ_STATUS_DC_Y_IRQS          BIT_8
#define IRQ_STATUS_LINEIRQRS          BIT_7
#define IRQ_STATUS_FIFOFULLIRQS      BIT_6
#define IRQ_STATUS_SOF2IRQS         BIT_5
#define IRQ_STATUS_SOF1IRQS        BIT_4
#define IRQ_STATUS_SOF0IRQS         BIT_3
#define IRQ_STATUS_EOF2IRQS         BIT_2
#define IRQ_STATUS_EOF1IRQS         BIT_1
#define IRQ_STATUS_EOF0IRQS         BIT_0



//Image Size Register
#define IMG_SIZE_HSIZE_MSK       SHIFT0(0x3ff)
#define IMG_SIZE_HSIZE_BASE         0
#define IMG_SIZE_VSIZE_MSK       SHIFT16(0x1ff)
#define IMG_SIZE_VSIZE_BASE         16

//Image Offset Register
#define IMG_OFFSET_HOFF_MSK       SHIFT0(0x3ff)
#define IMG_OFFSET_HOFF_BASE         0
#define IMG_OFFSET_VOFF_MSK       SHIFT16(0x1ff)
#define IMG_OFFSET_VOFF_BASE         16


//Control 0 Register
#define CTRL_0_SIFMODE_MSK  SHIFT30(0x3)
#define CTRL_0_SIFMODE_BASE   30
#define CTRL_0_DSCALE_MSK  SHIFT27(0x7)
#define CTRL_0_DSCALE_BASE   27
#define CTRL_0_YUVINFMT_MSK  SHIFT18(0x3)
#define CTRL_0_YUVINFMT_BASE   18
#define CTRL_0_YUVENDFMT_MSK  SHIFT16(0x3)
#define CTRL_0_YUVENDFMT_BASE   16
#define CTRL_0_YUVOUTFMT_MSK  SHIFT13(0x7)
#define CTRL_0_YUVOUTFMT_BASE   13
#define CTRL_0_RGBINOUTFMT_MSK  SHIFT9(0x7)
#define CTRL_0_RGBINOUTFMT_BASE   9
#define CTRL_0_DOUTFMT_MSK  SHIFT7(0x3)
#define CTRL_0_DOUTFMT_BASE   7
#define CTRL_0_DINFMT_MSK  SHIFT5(0x3)
#define CTRL_0_DINFMT_BASE   5
#define CTRL_0_RGBENDFMT_MSK  SHIFT2(0x3)
#define CTRL_0_RGBENDFMT_BASE   2

#define CTRL_0_VCLKPOL   BIT_26
#define CTRL_0_VPOL   BIT_25
#define CTRL_0_HPOL   BIT_24
#define CTRL_0_VEDGE_CTRL   BIT_23
#define CTRL_0_EOF_CTRL   BIT_22
#define CTRL_0_EOFFLUSH   BIT_21
#define CTRL_0_RGBOUTEND   BIT_12
#define CTRL_0_EN   BIT_0

//Control 1 Register
#define CTRL_1_DMA_DONE_SEL   BIT_31
#define CTRL_1_DMA_POSTED_SEL   BIT_30
#define CTRL_1_SRAMPDWN   BIT_29
#define CTRL_1_PWRDNEN   BIT_28
#define CTRL_1_FRMNUMSEL   BIT_27
#define CTRL_1_YUV420SEL   BIT_24
#define CTRL_1_IRE_IF_SEL   BIT_19
#define CTRL_1_LCD_IF_SEL   BIT_18
#define CTRL_1_BAR_SCAN_IF_ENA   BIT_16
#define CTRL_1_DMA_FAST_QR   BIT_11
#define CTRL_1_DMA_FAST_QW   BIT_10
#define CTRL_1_DESC_MODE   BIT_9
#define CTRL_1_DESC_ENA   BIT_8
#define CTRL_1_SENSORCLKGATE   BIT_0

#define CTRL_1_DMABRSTSEL_MSK  SHIFT25(0x3) 
#define CTRL_1_DMABRSTSEL_BASE   25

#define CTRL_1_RGBALPHA_MSK  SHIFT20(0xf) 
#define CTRL_1_RGBALPHA_BASE   20

#define CTRL_1_Always1E_MSK  SHIFT1(0x1f) 
#define CTRL_1_Always1E_BASE   1

//Control 2 Register
#define CTRL_2_JIRA_MMP31018 BIT_31
#define CTRL_2_JIRA_MMP3985 BIT_30
#define CTRL_2_LINEBUFNUMENA BIT_16
#define CTRL_2_LINECNTIRQ_MSK  SHIFT0(0x1fff)
#define CTRL_2_LINECNTIRQ_BASE    0
#define CTRL_2_LINEBUFCNT_MSK  SHIFT17(0x1fff)
#define CTRL_2_LINEBUFCNT_BASE    17

//Clock Control Register
#define CLOCK_CTRL_CLKDIV_MSK   SHIFT0(0xffff)
#define CLOCK_CTRL_CLKDIV_BASE    0
#define CLOCK_CTRL_CLKFT_MSK   SHIFT16(0xfff)
#define CLOCK_CTRL_CLKFT_BASE    16
#define CLOCK_CTRL_INTPIXCLKSEL_MSK   SHIFT29(0x3)
#define CLOCK_CTRL_INTPIXCLKSEL_BASE    29


//SRAM TC0 Register (Test Only)
#define SRAM_TC0_TEST_ONLY_DESC_VFIFO_RTC_MSK SHIFT22(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_VFIFO_RTC_BASE  22
#define SRAM_TC0_TEST_ONLY_DESC_VFIFO_WTC_MSK SHIFT20(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_VFIFO_WTC_BASE  20
#define SRAM_TC0_TEST_ONLY_DESC_UFIFO_RTC_MSK SHIFT18(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_UFIFO_RTC_BASE  18
#define SRAM_TC0_TEST_ONLY_DESC_UFIFO_WTC_MSK SHIFT16(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_UFIFO_WTC_BASE  16
#define SRAM_TC0_TEST_ONLY_DESC_YFIFO_RTC_MSK SHIFT14(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_YFIFO_RTC_BASE  14
#define SRAM_TC0_TEST_ONLY_DESC_YFIFO_WTC_MSK SHIFT12(0x3)
#define SRAM_TC0_TEST_ONLY_DESC_YFIFO_WTC_BASE  12
#define SRAM_TC0_TEST_ONLY_VFIFO_RTC_MSK SHIFT10(0x3)
#define SRAM_TC0_TEST_ONLY_VFIFO_RTC_BASE  10
#define SRAM_TC0_TEST_ONLY_VFIFO_WTC_MSK SHIFT8(0x3)
#define SRAM_TC0_TEST_ONLY_VFIFO_WTC_BASE  8
#define SRAM_TC0_TEST_ONLY_UFIFO_RTC_MSK SHIFT6(0x3)
#define SRAM_TC0_TEST_ONLY_UFIFO_RTC_BASE  6
#define SRAM_TC0_TEST_ONLY_UFIFO_WTC_MSK SHIFT4(0x3)
#define SRAM_TC0_TEST_ONLY_UFIFO_WTC_BASE  4
#define SRAM_TC0_TEST_ONLY_YFIFO_RTC_MSK SHIFT2(0x3)
#define SRAM_TC0_TEST_ONLY_YFIFO_RTC_BASE  2
#define SRAM_TC0_TEST_ONLY_YFIFO_WTC_MSK SHIFT0(0x3)
#define SRAM_TC0_TEST_ONLY_YFIFO_WTC_BASE  0

//MIPI CSI2 Control 0 Register
#define CSI2_CTRL_0_SRAMPDWN_MSK   SHIFT28(0x7)
#define CSI2_CTRL_0_SRAMPDWN_BASE   28
#define CSI2_CTRL_0_SRAMTC_MSK   SHIFT16(0xfff)
#define CSI2_CTRL_0_SRAMTC_BASE   16
#define CSI2_CTRL_0_VLEN_MSK   SHIFT4(0xf)
#define CSI2_CTRL_0_VLEN_BASE   4
#define CSI2_CTRL_0_LNMUM_MSK   SHIFT1(0x3)
#define CSI2_CTRL_0_LNMUM_BASE   1
#define CSI2_CTRL_0_GLP_MASK   BIT_12
#define CSI2_CTRL_0_EOT   BIT_11
#define CSI2_CTRL_0_PARERR   BIT_10
#define CSI2_CTRL_0_ECCEND   BIT_9
#define CSI2_CTRL_0_BITEND   BIT_8
#define CSI2_CTRL_0_EXT_TIM_ENA   BIT_3
#define CSI2_CTRL_0_ENA   BIT_0


//MIPI CSI2 IRQ Raw Status Register
#define CSI2_IRQ_RAW_STATUS_CSI2LNOVRIRQ_MSK  SHIFT24(0xf)
#define CSI2_IRQ_RAW_STATUS_CSI2LNOVRIRQ_BASE   24
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNSOTERRIRQ_MSK  SHIFT12(0xf)
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNSOTERRIRQ_BASE  12
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNSOTSYNCERRIRQ_MSK  SHIFT8(0xf)
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNSOTSYNCERRIRQ_BASE  8
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNERRCONTROLIRQ_MSK  SHIFT4(0xf)
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNERRCONTROLIRQ_BASE  4
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNULPSACTIVEIRQ_MSK  SHIFT0(0xf)
#define CSI2_IRQ_RAW_STATUS_MIPIDPHYLNULPSACTIVEIRQ_BASE  0


//MIPI CSI2 Virtual Channel Control Register
#define CSI2_VCCTRL_VC1_MSK   SHIFT22(0x3)
#define CSI2_VCCTRL_VC1_BASE   22
#define CSI2_VCCTRL_DT1_MSK   SHIFT16(0x3f)
#define CSI2_VCCTRL_DT1_BASE   16
#define CSI2_VCCTRL_VC0_MSK   SHIFT14(0x3)
#define CSI2_VCCTRL_VC0_BASE   14
#define CSI2_VCCTRL_MD_MSK   SHIFT0(0x3)
#define CSI2_VCCTRL_MD_BASE   0

//MIPI CSI2 Virtual Channel Control Register
#define CSI2_VCCTRL2_GSP_PDFVSSM  BIT_11
#define CSI2_VCCTRL2_GSP_PDLVMC  BIT_10
#define CSI2_VCCTRL2_LN4_PDFVSSM  BIT_9
#define CSI2_VCCTRL2_LN4_PDLVMC  BIT_8
#define CSI2_VCCTRL2_LN3_PDFVSSM  BIT_7
#define CSI2_VCCTRL2_LN3_PDLVMC  BIT_6
#define CSI2_VCCTRL2_LN2_PDFVSSM  BIT_5
#define CSI2_VCCTRL2_LN2_PDLVMC  BIT_4
#define CSI2_VCCTRL2_LN1_PDFVSSM  BIT_3
#define CSI2_VCCTRL2_LN1_PDLVMC  BIT_2
#define CSI2_VCCTRL2_LN0_PDFVSSM  BIT_1
#define CSI2_VCCTRL2_LN0_PDLVMC  BIT_0


//MIPI CSI2 DPHY 3 Register
#define CSI2_DPHY3_GSP_MASK_MSK  SHIFT16(0xff)
#define CSI2_DPHY3_GSP_MASK_BASE    16
#define CSI2_DPHY3_HS_SETTLE_MSK  SHIFT8(0xff)
#define CSI2_DPHY3_HS_SETTLE_BASE    8
#define CSI2_DPHY3_HS_TERM_ENA_MSK  SHIFT0(0xff)
#define CSI2_DPHY3_HS_TERM_ENA_BASE    0

//MIPI CSI2 DPHY 5 Register
#define CSI2_DPHY5_MIPI_REN_MSK   SHIFT9(0xff)
#define CSI2_DPHY5_MIPI_REN_BASE   9
#define CSI2_DPHY5_LANE_RESC_ENA_MSK   SHIFT4(0xf)
#define CSI2_DPHY5_LANE_RESC_ENA_BASE   4
#define CSI2_DPHY5_LANE_ENA_MSK   SHIFT0(0xf)
#define CSI2_DPHY5_LANE_ENA_BASE   0
#define CSI2_DPHY5_RCOMP_VLD  BIT_8


//MIPI CSI2 DPHY 6 Register
#define CSI2_DPHY6_BG_VREF_ENA  BIT_26
#define CSI2_DPHY6_RCOMP_LOAD BIT_25
#define CSI2_DPHY6_RCOMP_CLK_SEL  BIT_24
#define CSI2_DPHY6_REN_BYPASS_MSK   SHIFT16(0xff)
#define CSI2_DPHY6_REN_BYPASS_BASE    16
#define CSI2_DPHY6_CK_SETTLE_MSK   SHIFT8(0xff)
#define CSI2_DPHY6_CK_SETTLE_BASE    8
#define CSI2_DPHY6_CK_TERM_ENA_MSK   SHIFT0(0xff)
#define CSI2_DPHY6_CK_TERM_ENA_BASE    0


//MIPI CSI2 reset  Register
#define CCIC_CSI2_reset_hresetn_ahbs          BIT_6
#define CCIC_CSI2_reset_ipe_hclkgate_rstn     BIT_5
#define CCIC_CSI2_reset_ipe_vclkgate_rst      BIT_4
#define CCIC_CSI2_reset_csi2_rstn             BIT_3
#define CCIC_CSI2_reset_preset                BIT_2
#define CCIC_CSI2_reset_isim_vreset           BIT_1
#define CCIC_CSI2_reset_csi2_vreset           BIT_0

//Descriptor Chain Control Y Register
#define DESC_CHAIN_CTRLY_TNL_MSK  SHIFT28(0xf)
#define DESC_CHAIN_CTRLY_TNL_BASE   28
#define DESC_CHAIN_CTRLY_TL_MSK  SHIFT3(0x1fffff)
#define DESC_CHAIN_CTRLY_TL_BASE   3
#define DESC_CHAIN_CTRLY_IC    BIT_24


//Descriptor Chain Control U Register
#define DESC_CHAIN_CTRLU_TNL_MSK  SHIFT28(0xf)
#define DESC_CHAIN_CTRLU_TNL_BASE   28
#define DESC_CHAIN_CTRLU_TL_MSK  SHIFT3(0x1fffff)
#define DESC_CHAIN_CTRLU_TL_BASE   3
#define DESC_CHAIN_CTRLU_IC    BIT_24

//Descriptor Chain Control V Register
#define DESC_CHAIN_CTRLV_TNL_MSK  SHIFT28(0xf)
#define DESC_CHAIN_CTRLV_TNL_BASE   28
#define DESC_CHAIN_CTRLV_TL_MSK  SHIFT3(0x1fffff)
#define DESC_CHAIN_CTRLV_TL_BASE   3
#define DESC_CHAIN_CTRLV_IC    BIT_24




#endif
