/******************************************************************************
 *
 * Name:	ICU.h
 * Project:	Marvell Registers
 * Purpose:	Marvell Registers
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2013 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	ICU.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_ICU_H
#define	__INC_ICU_H


 
typedef struct
{
	__IO uint32_t	INT_CFGx[64];						/* 0x00FC 32 bit	Interrupt 0 to
											 *			63 Configuration
											 *			Registers
											 */
	__IO uint32_t	SEAGULL_FIQ_SEL_INT_NUM;		/* 0x0100 32 bit	<var Processor:
											 *			Osprey> FIQ Selected
											 *			Interrupt Number
											 *			Register
											 */
	__IO uint32_t	SEAGULL_IRQ_SEL_INT_NUM;		/* 0x0104 32 bit	<var Processor:
											 *			Osprey> IRQ Selected
											 *			Interrupt Number
											 *			Register
											 */
	__IO uint32_t	MOHAWK_FIQ_SEL_INT_NUM;			/* 0x0108 32 bit	<var Processor:
											 *			Mohawk> FIQ Selected
											 *			Interrupt Number
											 *			Register
											 */
	__IO uint32_t	MOHAWK_IRQ_SEL_INT_NUM;			/* 0x010C 32 bit	<var Processor:
											 *			Mohawk> IRQ Selected
											 *			Interrupt Number
											 *			Register
											 */
	__IO uint32_t	SEAGULL_GBL_IRQ_MSK;			/* 0x0110 32 bit	<var Processor:
											 *			Osprey> Global
											 *			Interrupt Mask
											 *			Register
											 */
	__IO uint32_t	MOHAWK_GBL_IRQ_MSK;				/* 0x0114 32 bit	<var Processor:
											 *			Mohawk> Global
											 *			Interrupt Mask
											 *			Register
											 */
	__IO uint32_t	DMA_SEAGULL_INT_MSK;			/* 0x0118 32 bit	DMA <var
											 *			Processor: Osprey>
											 *			Interrupt Mask
											 *			Register
											 */
	__IO uint32_t	DMA_MOHAWK_INT_MSK;				/* 0x011C 32 bit	DMA <var
											 *			Processor: Mohawk>
											 *			Interrupt Mask
											 *			Register
											 */
	__IO uint32_t	DMA_SEAGULL_INT_STATUS;			/* 0x0120 32 bit	DMA <var
											 *			Processor: Osprey>
											 *			Interrupt Status
											 *			Register
											 */
	__IO uint32_t	DMA_MOHAWK_INT_STATUS;			/* 0x0124 32 bit	DMA <var
											 *			Processor: Mohawk>
											 *			Interrupt Status
											 *			Register
											 */
	__IO uint32_t	INT_STATUS_0;					/* 0x0128 32 bit	Interrupt Status
											 *			Register 0 
											 */
	__IO uint32_t	INT_STATUS_1;					/* 0x012C 32 bit	Interrupt Status
											 *			Register 1 
											 */
	__IO uint32_t	DDR_ARM_L2_INT_MSK;				/* 0x0130 32 bit	DDR and ARM L2
											 *			Cache Interrupt Mask
											 *			Register
											 */
	__IO uint32_t	DDR_ARM_L2_INT_STATUS;			/* 0x0134 32 bit	DDR and ARM L2
											 *			Cache Interrupt
											 *			Status Register
											 */
}ICU_TypeDef;


#define	ICU_BASE	0xD4282000
#define	ICU	((ICU_TypeDef*)ICU_BASE)


/*
 *
 *	THE BIT DEFINES
 *
 */
/*	ICU_CFG_x[64]				0x0000	Interrupt 0 to 63 Configuration
 *										Registers
 */
/*		Bit(s) ICU_CFG_X_RSRV_ reserved */
/* <var Processor: Mohawk> Interrupt */
#define	ICU_CFG_X_MOHAWK_INT				BIT_6				
/* <var Processor: Osprey> Interrupt */
#define	ICU_CFG_X_SEAGULL_INT				BIT_5				
#define	ICU_CFG_X_IRQ_FIQ					BIT_4				/* IRQ/FIQ */
#define	ICU_CFG_X_PRIORITY_MASKING_MSK		SHIFT0(0xf)			/* Priority/Masking */
#define	ICU_CFG_X_PRIORITY_MASKING_BASE		0

/*	ICU_SEAGULL_FIQ_SEL_INT_NUM	0x0100	<var Processor: Osprey> FIQ Selected
 *										Interrupt Number Register
 */
/*		Bit(s) ICU_SEAGULL_FIQ_SEL_INT_NUM_RSRV_ reserved */
/* Interrupt Pending */
#define	ICU_SEAGULL_FIQ_SEL_INT_NUM_INT_PENDING				BIT_6				
/* Selected Interrupt Number */
#define	ICU_SEAGULL_FIQ_SEL_INT_NUM_SEL_INT_NUM_MSK			SHIFT0(0x3f)		
#define	ICU_SEAGULL_FIQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_SEAGULL_IRQ_SEL_INT_NUM	0x0104	<var Processor: Osprey> IRQ Selected
 *										Interrupt Number Register
 */
/*		Bit(s) ICU_SEAGULL_IRQ_SEL_INT_NUM_RSRV_ reserved */
/* Interrupt Pending */
#define	ICU_SEAGULL_IRQ_SEL_INT_NUM_INT_PENDING				BIT_6				
/* Selected Interrupt Number */
#define	ICU_SEAGULL_IRQ_SEL_INT_NUM_SEL_INT_NUM_MSK			SHIFT0(0x3f)		
#define	ICU_SEAGULL_IRQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_MOHAWK_FIQ_SEL_INT_NUM	0x0108	<var Processor: Mohawk> FIQ Selected
 *										Interrupt Number Register
 */
/*		Bit(s) ICU_MOHAWK_FIQ_SEL_INT_NUM_RSRV_ reserved */
/* Interrupt Pending */
#define	ICU_MOHAWK_FIQ_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_MOHAWK_FIQ_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_MOHAWK_FIQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_MOHAWK_IRQ_SEL_INT_NUM	0x010C	<var Processor: Mohawk> IRQ Selected
 *										Interrupt Number Register
 */
/*		Bit(s) ICU_MOHAWK_IRQ_SEL_INT_NUM_RSRV_ reserved */
/* Interrupt Pending */
#define	ICU_MOHAWK_IRQ_SEL_INT_NUM_INT_PENDING			BIT_6				
/* Selected Interrupt Number */
#define	ICU_MOHAWK_IRQ_SEL_INT_NUM_SEL_INT_NUM_MSK		SHIFT0(0x3f)		
#define	ICU_MOHAWK_IRQ_SEL_INT_NUM_SEL_INT_NUM_BASE		0

/*	ICU_SEAGULL_GBL_IRQ_MSK		0x0110	<var Processor: Osprey> Global
 *										Interrupt Mask Register
 */
/*		Bit(s) ICU_SEAGULL_GBL_IRQ_MSK_RSRV_ reserved */
#define	ICU_SEAGULL_GBL_IRQ_MSK_IRQ_MSK			BIT_1				/* Mask IRQ */
#define	ICU_SEAGULL_GBL_IRQ_MSK_FIQ_MSK			BIT_0				/* Mask FIQ */

/*	ICU_MOHAWK_GBL_IRQ_MSK		0x0114	<var Processor: Mohawk> Global
 *										Interrupt Mask Register
 */
/*		Bit(s) ICU_MOHAWK_GBL_IRQ_MSK_RSRV_ reserved */
#define	ICU_MOHAWK_GBL_IRQ_MSK_IRQ_MSK			BIT_1				/* Mask IRQ */
#define	ICU_MOHAWK_GBL_IRQ_MSK_FIQ_MSK			BIT_0				/* Mask FIQ */

/*	ICU_DMA_SEAGULL_INT_MSK		0x0118	DMA <var Processor: Osprey> Interrupt
 *										Mask Register
 */
/* DMA <var Processor: Osprey> Interrupt Mask */
#define	ICU_DMA_SEAGULL_INT_MSK_DMA_SEAGULL_INT_MSK_MSK			SHIFT0(0xffffffff)	
#define	ICU_DMA_SEAGULL_INT_BASE_DMA_SEAGULL_INT_BASE_BASE		0

/*	ICU_DMA_MOHAWK_INT_MSK		0x011C	DMA <var Processor: Mohawk> Interrupt
 *										Mask Register
 */
/* DMA <var Processor: Mohawk> Interrupt Mask */
#define	ICU_DMA_MOHAWK_INT_MSK_DMA_MOHAWK_INT_MSK_MSK			SHIFT0(0xffffffff)	
#define	ICU_DMA_MOHAWK_INT_BASE_DMA_MOHAWK_INT_BASE_BASE		0

/*	ICU_DMA_SEAGULL_INT_STATUS	0x0120	DMA <var Processor: Osprey> Interrupt
 *										Status Register
 */
/* DMA <var Processor: Osprey> Interrupt Status */
#define	ICU_DMA_SEAGULL_INT_STATUS_DMA_SEAGULL_INT_STATUS_MSK		SHIFT0(0xffffffff)	
#define	ICU_DMA_SEAGULL_INT_STATUS_DMA_SEAGULL_INT_STATUS_BASE		0

/*	ICU_DMA_MOHAWK_INT_STATUS	0x0124	DMA <var Processor: Mohawk> Interrupt
 *										Status Register
 */
/* DMA Interrupt 1 Status */
#define	ICU_DMA_MOHAWK_INT_STATUS_DMA_INT1_STATUS_MSK		SHIFT0(0xffffffff)	
#define	ICU_DMA_MOHAWK_INT_STATUS_DMA_INT1_STATUS_BASE		0

/*	ICU_INT_STATUS_0			0x0128	Interrupt Status Register 0 */
/* Interrupt Status [31:0] */
#define	ICU_INT_STATUS_0_INT_STATUS_0_MSK		SHIFT0(0xffffffff)	
#define	ICU_INT_STATUS_0_INT_STATUS_0_BASE		0

/*	ICU_INT_STATUS_1			0x012C	Interrupt Status Register 1 */
/* Interrupt Status [63:32] */
#define	ICU_INT_STATUS_1_INT_STATUS_1_MSK		SHIFT0(0xffffffff)	
#define	ICU_INT_STATUS_1_INT_STATUS_1_BASE		0

/*	ICU_DDR_ARM_L2_INT_MSK		0x0130	DDR and ARM L2 Cache Interrupt Mask
 *										Register
 */
/*		Bit(s) ICU_DDR_ARM_L2_INT_MSK_RSRV_ reserved */
/* <var Processor: Mohawk> L2 PA ECC Interrupt Mask */
#define	ICU_DDR_ARM_L2_INT_MSK_CA7_CNTPSIRQ_MSK			BIT_3				
/* <var Processor: Osprey> L2 UECC Interrupt Mask */
#define	ICU_DDR_ARM_L2_INT_MSK_CA7_CNTPNSIRQ_MSK		BIT_2				
/* <var Processor: Osprey> L2 ECC Interrupt Mask */
#define	ICU_DDR_ARM_L2_INT_MSK_CA7_CNTHPIRQ_MSK			BIT_1				
/* <var Processor: Osprey> L2 PA ECC Interrupt Mask */
#define	ICU_DDR_ARM_L2_INT_MSK_CA7_CNTVIRQ_MSK			BIT_0				

/*	ICU_DDR_ARM_L2_INT_STATUS	0x0134	DDR and ARM L2 Cache Interrupt Status
 *										Register
 */
/*		Bit(s) ICU_DDR_ARM_L2_INT_STATUS_RSRV_ reserved */
/* <var Processor: Mohawk> L2 PA ECC Interrupt Status */
#define	ICU_DDR_ARM_L2_INT_STATUS_CA7_CNTPSIRQ_STATUS		BIT_3				
/* <var Processor: Osprey> L2 UECC Interrupt Status */
#define	ICU_DDR_ARM_L2_INT_STATUS_CA7_CNTPNSIRQ_STATUS		BIT_2				
/* <var Processor: Osprey> L2 ECC Interrupt Status */
#define	ICU_DDR_ARM_L2_INT_STATUS_CA7_CNTHPIRQ_STATUS		BIT_1				
/* <var Processor: Osprey> L2 PA ECC Interrupt Status */
#define	ICU_DDR_ARM_L2_INT_STATUS_CA7_CNTVIRQ_STATUS		BIT_0				



/* -------------------- */


#endif	/* __INC_ICU_H */
